"use client";

import '@/shared/styles/global.css';
import { TerminalContextProvider } from "react-terminal";


export default function gameLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name='title' content="Create Next App"/>
      <meta name='description' content="Generated by create next app"/>
      <body>
        <TerminalContextProvider>
            {children}
        </TerminalContextProvider>
      </body>
    </html>
  );
}